---
- hosts: localhost
  become: true
  gather_facts: true
  tasks:
# update necessary variables before using the playbook
   - name: Install aptitude using apt
     apt:
       name: aptitude
       state: latest
       update_cache: yes
       force_apt_get: yes

   - name: Install required system packages
     apt:
       pkg:
       - ca-certificates
       - curl
       - software-properties-common
       - python-pip
       - virtualenv
       - python3-setuptools

   - name: Add docker gpg apt key
     apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

   - name: Add docker repository
     apt_repository:
       repo: deb https://download.docker.com/linux/ubuntu bionic stable
       state: present

   - name: Update apt and install docker-ce
     apt:
       update_cache: yes
       name: docker-ce
       state: latest

   - name: Install docker module for python
     pip:
       name: docker

   - name: Start and enable docker
     service:
       name: docker
       state: started
       enabled: yes

   - name: Add user to Docker group
     user:
       name: student
       groups: docker
       append: yes

   - name: Downloading docker-compose binaries
     shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

   - name: Updating permission of downloaded file.
     shell: sudo chmod +x /usr/local/bin/docker-compose  

